### PR TITLE
Implement the popup code box

### PR DESCRIPTION
**Pull request by leovincentseles**
- Implement the **popup** code box
- Fix **python3** display bug
- Change the variable color of **java** code

### CODE REVIEW

**Review by jasonisgod — CHANGES_REQUESTED** [review]
.

**Comment by leovincentseles** [comment]
Thanks for your kindly reminder.
I have submit additional commit.

**Comment by jasonisgod** [comment]
Merge conflicts due to my latest push

**Comment by leovincentseles** [comment]
The conflict is solved.

**Pull request merged**
